// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSrmhyVCir_JiVuAVX5_bn5OmMQLfTWzw',
    appId: '1:470643046322:web:a2ad9baf53fe51118096ab',
    messagingSenderId: '470643046322',
    projectId: 'task-3-notification',
    authDomain: 'task-3-notification.firebaseapp.com',
    storageBucket: 'task-3-notification.appspot.com',
    measurementId: 'G-HJELBRZ923',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPj9JDi8pzNDPwnyMZeiAerGES8ERZtrU',
    appId: '1:470643046322:android:a38f777ba8bc24948096ab',
    messagingSenderId: '470643046322',
    projectId: 'task-3-notification',
    storageBucket: 'task-3-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD95krTO-bX623bvHdaeBHTRYEYo-qfjPU',
    appId: '1:470643046322:ios:4d6a65cba25ac94d8096ab',
    messagingSenderId: '470643046322',
    projectId: 'task-3-notification',
    storageBucket: 'task-3-notification.appspot.com',
    iosClientId: '470643046322-au20tp1go1n3phc45g4pb2v4rrebvvd4.apps.googleusercontent.com',
    iosBundleId: 'com.example.task3Notifications',
  );
}
